### ISSUE TITLE
Multiple occurrences of the same host are hard to discern when "up"

### ISSUE THREAD

**Issue by jamiesmith** [elastic/uptime#10]
**Is your feature request related to a problem? Please describe.**
When I have multiple http/s entries against the same host (multiple routes) I can't see which is which:

![image](https://user-images.githubusercontent.com/220994/53251077-cc72b600-3689-11e9-8cca-f95a19ee8e6d.png)
Whereas in the ones that are down you can tell
![image](https://user-images.githubusercontent.com/220994/53251109-e0b6b300-3689-11e9-9487-3a9cd1c95bbb.png)

**Describe the solution you'd like**
I am torn - there are two or more options -
1. Show everything with the full URL
2. If there are multiple versions with the same URL, on the top level page just summarize and show percentages having trouble, then provide an intermediary drill-down page which would take you to the current click-through page
2a. if there is only one, then skip the intermediary page and go directly to the current click-through

**Describe alternatives you've considered**
Part of above.  Another option would be to allow me to change what shows up in the host column

**Additional context**
Here are the relevant parts of my config:

```
heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - "https://www.elastic.co"
    - "http://www.elastic.co"
  check.response.status: 200
- type: http
  schedule: '@every 5s'
  urls:
    - "https://www.elastic.co/solutions/apm"
  check.response:
    status: 200
    body: "Open Source Application Performance Monitoring"
- type: http
  schedule: '@every 5s'
  urls:
    - "https://www.elastic.co/solutions/security-analytics"
  check.response:
    body: "Can't find this"
```
