### ISSUE TITLE
[Brainstorm] Geo support for Uptime with Elastic Agent

### ISSUE THREAD

**Issue by ruflin** [elastic/uptime#251]
When running Elastic Agent for Uptime (heartbeat) one of the important informations is about where this Agent is running. The same monitors are run in different locations to get a global view on how services are doing. This geo information is added to each event.

This issue is to brainstorm on how this could work with Elastic Agent, Fleet in Cloud or on Prem.

To have each even enriched with the geo information, this geo information must be available locally to the Agent. There are multiple ways to make it available:

* Have it hardcoded in the config
* Environment variables
* Separate file with the info
* Shipped down from Fleet

In all the above cases, the Agent needs a way to make sense of this data based on a configuration file. The Agent is getting variable and conditions support soon (https://github.com/elastic/beats/pull/20839) and I think this is the perfect feature to be used here.

Lets assume for a moment that the agent is aware of the geo information either through the info from the agent or environment variables. A config (simplified) could then look as following:

```
inputs:
  - type: monitor/http
    processors:
      - add_field:
          host.geo: ${env.host.geo|host.geo}
```

This same config could be shipped to many agents across the globe and we ship the correct info.

This could be taken further with conditions:

```
inputs:
  - type: monitor/http
    processors:
      - add_field:
          host.geo: ${env.host.geo|host.geo}
    condition: ${geo.host} != us-west-1
```

This monitor gets run everywhere except on `us-west-1`. Of course, conditions could be more complex.

Lets get back on how the geo information could be provided.

1. Elastic Agent Metadata in Fleet: A user could enrich each Agent with metadata which is shipped down to the Agent and then could be used as variables
2. Local environment variables: The host machine contains environment variables for the geo information
3. Part of the config: The variables are provided in the local provider

Method 2 and 3 should work in any environment. For 2 a convention can be defined on which environment variables must be set. In the case of Cloud, I would expect that the correct metadata is already set automatically, if the user runs it on prem, he is requested to set it in environment variables or trough the agent metadata. As I would consider the geo data to be important not only important for uptime, we could make this a field in the agent metadata to be filled out.

**Comment by ruflin** [comment]
@andrewvc @blakerouse @ph Let me know what you think. I opened this to have it written down somewhere and get feedback on it.

**Comment by blakerouse** [comment]
@ruflin I think this is a perfect example of a `geo` provider with the new variable substitution work. Difference is that I think we should create a specific `geo` provider.

With a specific `geo` provider we can configure the provider manually if needed or have options on that specific provider.

```
providers:
  geo:
    lat: ...
    lng: ...
```

The geo provider could also perform checks to determine if running on a public cloud and auto set the lat, lng.
