### ISSUE TITLE
improve getting started experience

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/uptime#259]
Uptime has a good getting started experience, and the anomaly detection button on each monitor is wonderful.  Unfortunately, the anomaly detection requires location (`observer.geo.name`) and the basic configuration provided in the getting started (Elastic Home > Add Metric Data > Uptime) does not provide location info in the snippet.  Here is the example config:
```
heartbeat.monitors:
- type: http
  urls: ["http://elastic.co"]
  schedule: "@every 10s"
```

How about adding a second edit in the instructions it so that it includes `observer.geo.name`?  Like so (just uncommenting `geo` and `name`):
```
processors:
  - add_observer_metadata:
      # Optional, but recommended geo settings for the location Heartbeat is running in
      geo:
        # Token describing this location
        name: us-east-1a
        # Lat, Lon "
        #location: "37.926868, -78.024902"
```
