### ISSUE TITLE
Add environment field to Heartbeat / Uptime UI 

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#272]
**Is your feature request related to a problem? Please describe.**
 
Per @cyrille-leclerc 's suggestion ( https://github.com/elastic/beats/pull/20330#issuecomment-720989461 ) we should add an environment field to Heartbeat / Uptime, similar to how this is done in APM. Labeled environments are common, and already part of our synthetics solution, so this fits neatly. 

**Describe the solution you'd like**

We would add an environment field option to heartbeat monitors, and make it displayable and filterable in the Uptime UI alongside tags etc.

**Describe alternatives you've considered**

We could just use tags, but baking in environments makes a lot of sense in terms of correlating with APM and the fact that tags might be common across envs.

**Comment by drewpost** [comment]
I'm open to this. So I'm clear, the hierarchy of this would be a monitor has a service name and that monitor in a given service can also have an environment field?

cc @nehaduggal \

**Comment by cyrille-leclerc** [comment]
@drewpost we share the same understanding here with a slight difference: I thought of each monitor indicating a `service.name`and a `service.environment` when your phrasing suggests 2 levels of nesting.
My idea may be more verbose but easier to read thanks to the "flatness" of the data structure.

Here is a "mockup of the yaml configuration" that came to my mind:

```yml
# EXPERIMENT - NOT SUPPORTED CONFIGURATION SNIPPET
heartbeat.monitors:
- type: http
  id: www-frontend-monitor
  name: Website Frontend Monitor
  # hierarchical style for `service.name` and `service.environment`
  service:
    name: www-frontend
    environment: production
  urls: ["https://www.my-ecommerce-company.com/status"]
  schedule: '@every 10s'
  check.response.status: 200
  timeout: 2s
- type: http
  id: www-frontend-monitor-staging
  name: Website Frontend Monitor - Staging
  # flat-dot-separated style for `service.name` and `service.environment`
  service.name: www-frontend
  service.environment: staging
  urls: ["https://www.staging.my-ecommerce-company.com/status"]
  schedule: '@every 10s'
  check.response.status: 200
  timeout: 5s
```
