### ISSUE TITLE
display monitor.name instead of host value as a way to alias long urls

### ISSUE THREAD

**Issue by nabsource** [elastic/uptime#36]
**Is your feature request related to a problem? Please describe.**
The docs provide a way to alias the URL https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html#monitor-name but in the UI it maps to host. the host value can be autogenerated (think aws gateway), random and long. By adding the name configuration in the monitor yaml file, this should display a human readable name for this monitor

**Describe the solution you'd like**
if monitor.name value is set, display this in the frontend

**Describe alternatives you've considered**
possibly a new configuration setting to allow an alias (human readable name) to be displayed in the frontend of the Uptime UI

**Additional context**
kinda related, maybe https://github.com/elastic/uptime/issues/11

example:
```
- type: http
  schedule: '@every 60s'
  name: human-readable-name-for-this-monitor
  urls: 
    - "https://random123verylongsomethinghere.execute-api.az-blrg-1.amz.com/random.com/endpoint”
  check.request:
    method: GET
    headers:
      'Authorization': ‘something-secret’
  check.response:
    status: 200
```
