### ISSUE TITLE
Add Pagination to overview page

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#63]
The overview page table doesn't have pagination. This is a commonly requested feature we should implement. There are clear EUI guidelines/widgets for this already.

**Comment by shahzad31** [comment]
With this configuration 
```
heartbeat.monitors:
- type: http
  id: localhost
  name: localhost
  urls: ["http://localhost:9200"]
  schedule: '@every 10s'
- type: http
  id: elastic-co
  name: elastic
  urls: ["https://www.elastic.co"]
  schedule: '@every 10s'
  mode: all
- type: http
  id: andrewvc-com
  urls: ["http://blog.andrewvc.com"]
  schedule: '@every 10s'
  mode: all
- type: http
  id: secure-avc
  urls: ["https://blog.andrewvc.com"]
  schedule: '@every 10s'
  mode: all
- type: http
  id: bad-ssl
  urls: ["https://expired.badssl.com"]
  schedule: '@every 10s'
  mode: all 
- type: http
  id: kibana-local
  urls: ["http://localhost:5601/"]
  schedule: '@every 5s'
  mode: all
```

i don't see elastic-co monitor after i merged your branch into my local branch , let me know we can debug it together. It does says total six monitors, but only 5 rows are returned in monitor states.
![image](https://user-images.githubusercontent.com/3505601/66392308-e24ea480-e9e8-11e9-9f3e-449478e27e7d.png)
