### ISSUE TITLE
Heartbeats that have a `name` that includes parentheses cannot be filtered upon in uptime.

### ISSUE THREAD

**Issue by tadgh** [elastic/uptime#69]
**Describe the bug**
Uptime cannot filter by name on heartbeats that have parentheses in their name. 

**To Reproduce**
1. Use this heartbeat config for a monitor
```yaml
- type: http 
  name: name(paren)
  enabled: true
  schedule: '@every 30s' # every 5 seconds from start of beat
  urls: ["http://whatever.com"]
  ipv4: true
  mode: any
```
2. Head over to the uptime page. 
3.  Click on the `name` dropdown for filtering
4. Click on the field `name(paren)`

**Expected behavior**
Uptime filters upon this particular name

**Actual Behaviour**
Kibana frontend throws an error
```
Version: 7.2.0
Build: 24337
Error: uncaught exception: SyntaxError: Expected end of input or whitespace but "(" found. (:0)
window.onerror@https://apeee.ca/bundles/commons.bundle.js:3:1638720
```
