### ISSUE TITLE
Introduce a specific error message for invalid processor YAML

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#92]
**Is your feature request related to a problem? Please describe.**
We made a mistake when configuring Heartbeat's observer processor. We had something like:

```yaml
processors:
- add_observer_metadata:
  geo:
    name: "NAME"
    location: "39.1242, 75.4352"
```

and further down the file we also had...

```yaml
processors:
- add_observer_metadata
```

This configuration causes Heartbeat to run like normal but without embedding any location data.

**Describe the solution you'd like**
If possible, it would be better if we could alert the user to the misconfiguration, as this kind of thing could easily go unnoticed. An error message when starting up alerting them that the processor will not run in the current configuration would be better.

**Describe alternatives you've considered**
Heartbeat could stop running with an error.

**Additional context**
N/A
